spring:
  application:
    name: ifispinbot

telegram:
  botName: ${TELEGRAM_BOT_NAME}
  token: ${TELEGRAM_BOT_TOKEN}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

api:
  url: https://api.semanticscholar.org/graph/v1/
  fields: title,url,publicationDate
  searchPath: /paper/search/