spring:
  application:
    name: ifispinbot

telegram:
  botName: ${TELEGRAM_BOT_NAME}
  token: ${TELEGRAM_BOT_TOKEN}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

api:
  url: https://api.openalex.org
  path: /works
  apiKey: ${API_KEY}
  apiKeyParam: api_key
  searchParam: search
  filterParam: filter
  selectParam: select
  pageParam: page
  perPageParam: per_page

fast-api:
  host: ${FASTAPI_HOST}
  port: ${FASTAPI_PORT}